import React from 'react'
import MovieItem from './MovieItem'
import "./MovieRow.css"

function MovieRow(props) {
    return (
        <div className="Row">
            <h1 className='heading'>{props.heading}</h1>
            
            <div className="items">
                <MovieItem poster={`https://source.unsplash.com/random/720x1280?sig=${Math.random() * 100}`} title="Movie Name" description="They had no proof. He knew that they knew he had done it but they didn't have any proof. It was a huge distinction and it was the difference between him keeping his freedom or being locked away for decades. They continued to question him, probing him for information that they could use against him or find the proof they needed to put him away. He smiled and continued to block their every inquiry by feigning his innocence for a crime they all knew he committed."></MovieItem>
                <MovieItem poster={`https://source.unsplash.com/random/720x1280?sig=${Math.random() * 100}`} title="Movie Name" description="They had no proof. He knew that they knew he had done it but they didn't have any proof. It was a huge distinction and it was the difference between him keeping his freedom or being locked away for decades. They continued to question him, probing him for information that they could use against him or find the proof they needed to put him away. He smiled and continued to block their every inquiry by feigning his innocence for a crime they all knew he committed."></MovieItem>
                <MovieItem poster={`https://source.unsplash.com/random/720x1280?sig=${Math.random() * 100}`} title="Movie Name" description="They had no proof. He knew that they knew he had done it but they didn't have any proof. It was a huge distinction and it was the difference between him keeping his freedom or being locked away for decades. They continued to question him, probing him for information that they could use against him or find the proof they needed to put him away. He smiled and continued to block their every inquiry by feigning his innocence for a crime they all knew he committed."></MovieItem>
                <MovieItem poster={`https://source.unsplash.com/random/720x1280?sig=${Math.random() * 100}`} title="Movie Name" description="They had no proof. He knew that they knew he had done it but they didn't have any proof. It was a huge distinction and it was the difference between him keeping his freedom or being locked away for decades. They continued to question him, probing him for information that they could use against him or find the proof they needed to put him away. He smiled and continued to block their every inquiry by feigning his innocence for a crime they all knew he committed."></MovieItem>
                <MovieItem poster={`https://source.unsplash.com/random/720x1280?sig=${Math.random() * 100}`} title="Movie Name" description="They had no proof. He knew that they knew he had done it but they didn't have any proof. It was a huge distinction and it was the difference between him keeping his freedom or being locked away for decades. They continued to question him, probing him for information that they could use against him or find the proof they needed to put him away. He smiled and continued to block their every inquiry by feigning his innocence for a crime they all knew he committed."></MovieItem>
                <MovieItem poster={`https://source.unsplash.com/random/720x1280?sig=${Math.random() * 100}`} title="Movie Name" description="They had no proof. He knew that they knew he had done it but they didn't have any proof. It was a huge distinction and it was the difference between him keeping his freedom or being locked away for decades. They continued to question him, probing him for information that they could use against him or find the proof they needed to put him away. He smiled and continued to block their every inquiry by feigning his innocence for a crime they all knew he committed."></MovieItem>
                <MovieItem poster={`https://source.unsplash.com/random/720x1280?sig=${Math.random() * 100}`} title="Movie Name" description="They had no proof. He knew that they knew he had done it but they didn't have any proof. It was a huge distinction and it was the difference between him keeping his freedom or being locked away for decades. They continued to question him, probing him for information that they could use against him or find the proof they needed to put him away. He smiled and continued to block their every inquiry by feigning his innocence for a crime they all knew he committed."></MovieItem>
                <MovieItem poster={`https://source.unsplash.com/random/720x1280?sig=${Math.random() * 100}`} title="Movie Name" description="They had no proof. He knew that they knew he had done it but they didn't have any proof. It was a huge distinction and it was the difference between him keeping his freedom or being locked away for decades. They continued to question him, probing him for information that they could use against him or find the proof they needed to put him away. He smiled and continued to block their every inquiry by feigning his innocence for a crime they all knew he committed."></MovieItem>
                <MovieItem poster={`https://source.unsplash.com/random/720x1280?sig=${Math.random() * 100}`} title="Movie Name" description="They had no proof. He knew that they knew he had done it but they didn't have any proof. It was a huge distinction and it was the difference between him keeping his freedom or being locked away for decades. They continued to question him, probing him for information that they could use against him or find the proof they needed to put him away. He smiled and continued to block their every inquiry by feigning his innocence for a crime they all knew he committed."></MovieItem>
                <MovieItem poster={`https://source.unsplash.com/random/720x1280?sig=${Math.random() * 100}`} title="Movie Name" description="They had no proof. He knew that they knew he had done it but they didn't have any proof. It was a huge distinction and it was the difference between him keeping his freedom or being locked away for decades. They continued to question him, probing him for information that they could use against him or find the proof they needed to put him away. He smiled and continued to block their every inquiry by feigning his innocence for a crime they all knew he committed."></MovieItem>
                <MovieItem poster={`https://source.unsplash.com/random/720x1280?sig=${Math.random() * 100}`} title="Movie Name" description="They had no proof. He knew that they knew he had done it but they didn't have any proof. It was a huge distinction and it was the difference between him keeping his freedom or being locked away for decades. They continued to question him, probing him for information that they could use against him or find the proof they needed to put him away. He smiled and continued to block their every inquiry by feigning his innocence for a crime they all knew he committed."></MovieItem>
                
            </div>
        </div>
    )
}

export default MovieRow